export const consts = {
  circleRadius: 30,
  pathStrokeWidth: 5,
  minZoom: 0.1,
  maxZoom: 20,
  zoomSlowdown: 1000,
  panSlowdown: 2,
  playerTransition: 500,
  mapPositionRef: 'mapPositionRef',
  borderRadius: '10px',
  placeholderEmoji: `🫥`,
  temperIncrease: 3,
  temperDecrease: 0.5,
  eventInterval: 20,
  itemInterval: 3,
  customEase: 'cubic-bezier(0.8, 0, 0.2, 1)',
  customEaseOut: 'cubic-bezier(0.2, 1, 0.2, 1)',
}
