export const svg = document.querySelector<SVGElement>(`svg`)
export const translateGroup = document.querySelector<SVGGElement>(`g#translate`)
export const zoomGroup = document.querySelector<SVGGElement>(`g#zoom`)
export const mapGroup = document.querySelector<SVGGElement>(`g#map`)
export const playersGroup = document.querySelector<SVGGElement>(`g#players`)
export const hudGroup = document.querySelector<SVGGElement>(`g#hud`)
